### ISSUE TITLE
Recipes showup time issue

### ISSUE THREAD

**Issue by SlyyJacob** [Elecs-Mods/CraftingTable-IV#94]
I installed the mod into my custom modpack on 1.12 and the recipes in the crafting table iv show up quite slowly (say 5-10 recipes every few seconds can be a minute long process with many mods). The overall processing seems to be very slow, as crafting an item will make the crafting table to reprocess the recipes all over again.
Is that a general issue? Specific issue you haven't encountered yet? Could this be resolved by maybe creating a cache of the recipes, so it doesn't have to go through them again? Otherwise love your mod.

**Comment by MechanosG** [comment]
Same issue here.  Just seems really slow sometimes, especially the initial delay.  There's a mod called QuickerCrafting that does the same thing as this mod, except from your player inventory instead of a dedicated bench, and without multi-depth recipes..  and it loads recipes pretty much instantly, with no lag.  So I assume there must be some way(s) to optimize this.

**Comment by Elec332** [comment]
The recursion is what causes the delays. The recipes are cached, but every time you craft something the contents of your inventory change, so the list has to be recalculated.

What modpack are you using?

**Comment by MechanosG** [comment]
Dunno about OP, but I was using an unreleased modpack still being developed.  If it helps, that pack is/was using forge-14.23.5.2847 and CraftingTableIV-1.12.2-1.5.121.jar, which was up to date at the time.

**Comment by Elec332** [comment]
Closing for now, if it's still an issue please re-open an issue
